services:
  opensearchsearch:
    image: public.ecr.aws/opensearchproject/opensearch:${VERSION:-2}
    hostname: opensearchsearch
    environment:
      - cluster.name=opensearchsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.publish_host=127.0.0.1
      - logger.org.opensearchsearch=warn
      - path.repo=/usr/share/opensearchsearch/backup
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/backup:/usr/share/opensearchsearch/backup
    ports:
      - 9200:9200